### ISSUE TITLE
NameError: name '_vimspector_session' is not defined

### ISSUE THREAD

**Issue by rlaffers** [puremourning/vimspector#210]
**Describe the bug**
When pressing F5 or F9 I get this error:

```
Error detected while processing function vimspector#internal#state#Reset:                                                                                                                                         
line    9:
Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "/home/lri/.vim/pack/vimspector/opt/vimspector/python3/vimspector/debug_session.py", line 97
    self._logger.debug( f'Reading gadget config: {gadget_config_file}' )
                                                                     ^
SyntaxError: invalid syntax
Error detected while processing function vimspector#Continue:
line    1:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name '_vimspector_session' is not defined
```

**To Reproduce**
1. Download a vimspector release (1741).
2. Unpack it in ~/.vim/pack
3. Add the following into ~/.vimrc:
```
let g:vimspector_enable_mappings = 'HUMAN'
packadd! vimspector
```
4. cd ~/.vim/pack/vimspector/opt/vimspector/support/test/go/hello_world
5. vim hello-world.go
6. Press F5

Vimspector config file:

```
{
  "configurations": {
    "run": {
      "adapter": "vscode-go",
      "configuration": {
        "request": "launch",
        "program": "${workspaceRoot}/hello-world.go",
        "mode": "debug",
        "dlvToolPath": "$HOME/go/bin/dlv",
        "trace": true,
        "env": { "GO111MODULE": "off" }
      }
    }
  }
}
```

**Expected behavior**
To start debugging without errors.

**Actual behaviour**
The above error is displayed when I press F5 for the first time. Subsequently, when I press F5 again, I get:
```
Error detected while processing function vimspector#Continue:
line    1:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name '_vimspector_session' is not defined
```
The behavior is the same for pressing F9.

* Vimspector log (~/.vimspector.log):  **No such file exists**

**Environemnt**

VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jul 19 2020 12:22:01)

* Version of Vimspector: release 1741 [linux-daf854e3e1eeb51ed2b5c724b475a2aef1883b0e.tar.gz](https://github.com/puremourning/vimspector/releases/download/1741/linux-daf854e3e1eeb51ed2b5c724b475a2aef1883b0e.tar.gz)

* Output of `vim --version` or `nvim --version`

```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jul 19 2020 12:22:01)
Included patches: 1-1242
Modified by jonathon.fernyhough@york.ac.uk
Compiled by jonathon.fernyhough@york.ac.uk
Huge version with GTK2 GUI.  Features included (+) or not (-):
+acl               -farsi             +mouse_sgr         +tag_binary
+arabic            +file_in_path      -mouse_sysmouse    -tag_old_static
+autocmd           +find_in_path      +mouse_urxvt       -tag_any_white
+autochdir         +float             +mouse_xterm       +tcl
-autoservername    +folding           +multi_byte        +termguicolors
+balloon_eval      -footer            +multi_lang        +terminal
+balloon_eval_term +fork()            -mzscheme          +terminfo
+browse            +gettext           +netbeans_intg     +termresponse
++builtin_terms    -hangul_input      +num64             +textobjects
+byte_offset       +iconv             +packages          +textprop
+channel           +insert_expand     +path_extra        +timers
+cindent           +ipv6              +perl              +title
+clientserver      +job               +persistent_undo   +toolbar
+clipboard         +jumplist          +popupwin          +user_commands
+cmdline_compl     +keymap            +postscript        +vartabs
+cmdline_hist      +lambda            +printer           +vertsplit
+cmdline_info      +langmap           +profile           +virtualedit
+comments          +libcall           -python            +visual
+conceal           +linebreak         +python3           +visualextra
+cryptv            +lispindent        +quickfix          +viminfo
+cscope            +listcmds          +reltime           +vreplace
+cursorbind        +localmap          +rightleft         +wildignore
+cursorshape       +lua               +ruby              +wildmenu
+dialog_con_gui    +menu              +scrollbind        +windows
+diff              +mksession         +signs             +writebackup
+digraphs          +modify_fname      +smartindent       +X11
+dnd               +mouse             +sound             -xfontset
-ebcdic            +mouseshape        +spell             +xim
+emacs_tags        +mouse_dec         +startuptime       +xpm
+eval              +mouse_gpm         +statusline        +xsmp_interact
+ex_extra          -mouse_jsbterm     -sun_workshop      +xterm_clipboard
+extra_search      +mouse_netterm     +syntax            -xterm_save
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-2.0 -I/usr/lib/x86_64-linux-gnu/gtk-2.0/include -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/libpng12 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng12 -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/freetype2 -Wdate-time  -g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -D_REENTRANT -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: gcc   -L. -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -fstack-protector -rdynamic -Wl,-export-dynamic -Wl,-E  -Wl,-Bsymbolic-functions -fPIE -pie -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -o vim   -lgtk-x11-2.0 -lgdk-x11-2.0 -lpangocairo-1.0 -latk-1.0 -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lpangoft2-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lfontconfig -lfreetype -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE  -lm -ltinfo  -lselinux  -lcanberra -lacl -lattr -lgpm -ldl  -L/usr/lib -llua5.2 -Wl,-E  -fstack-protector-strong -L/usr/local/lib  -L/usr/lib/x86_64-linux-gnu/perl/5.22/CORE -lperl -ldl -lm -lpthread -lcrypt  -L/usr/lib/python3.5/config-3.5m-x86_64-linux-gnu -lpython3.5m -lpthread -ldl -lutil -lm -L/usr/lib/x86_64-linux-gnu -ltcl8.6 -ldl -lz -lpthread -lieee -lm -lruby-2.3 -lpthread -lgmp -ldl -lcrypt -lm
```

* Output of `which vim` or `which nvim`:

```
/usr/bin/vim
```

* Output of `:py3 pass`:

```
no output
```

* Output of `:py3 import vim`:

```
no output
```

I have python 3.5.2 installed.

* Operating system: Ubuntu 16.04.6 LTS (xenial)

**Additional context**
I tried debugging the cpp example - got the same problem. I also tried cloning the repo into ~/.vim/pack/vimspector/opt and using `install_gadget.py --enable-go` myself (it installed successfully with no errors) but I'm getting the same error when trying to debug.

Thank you for any help!

**Comment by puremourning** [comment]
>     self._logger.debug( f'Reading gadget config: {gadget_config_file}' )                                                                  ^
> SyntaxError: invalid syntax

https://github.com/puremourning/vimspector#dependencies

Sorry, your vim needs to be compiled against python 3.6 or later.

You can confirm the version with `:py3 print( __import__( 'sys' ).version )`

**Comment by puremourning** [comment]
I'm going to push a change to make this more obvious:

<img width="909" alt="Screenshot 2020-07-22 at 10 22 20" src="https://user-images.githubusercontent.com/10584846/88159458-3be53000-cc05-11ea-8cd4-eadc813fe484.png">
