### ISSUE TITLE
ModuleNotFoundError: No module named '_posixsubprocess'

### ISSUE THREAD

**Issue by harshasrisri** [puremourning/vimspector#222]
**Describe the bug**
```
Exception while loading vimspector: Vim(py3):ModuleNotFoundError: No module named '_posixsubprocess'
Vimspector unavailable: Requires Vim compiled with Python 3.6                                       
Press ENTER or type command to continue                                                             
```

**To Reproduce**
Trying to get the demo from https://puremourning.github.io/vimspector-web/demo-setup.html working. Whether I try to set a breakpoint or start debugging, I get the above error message.

Vimspector config file:
Same as the one in the demo link:
```
{
  "configurations": {
    "Vim - run a test": {
      "adapter": "vscode-cpptools",
      "configuration": {
        "type":    "cppdbg",
        "request": "launch",
        "program": "${workspaceRoot}/src/vim",
        "args": [
          "-f",
          "-u", "unix.vim",
          "-U", "NONE",
          "--noplugin",
          "--not-a-term",
          "-S", "runtest.vim",
          "${Test}.vim"
        ],
        "cwd": "${workspaceRoot}/src/testdir",
        "environment": [
          { "name": "VIMRUNTIME", "value": "${workspaceRoot}/runtime" }
        ],
        "externalConsole": true,
        "stopAtEntry": true,
        "MIMode": "lldb",
        "logging": {
          "engineLogging": false
        }
      }
    }
  }
}
```

**Expected behavior**
Breakpoint is set without error and debugging should start as described in the demo.

**Actual behaviour**
No breakpoint is set. Debugging won't start. I only see the above message and nothing happens after I press return.

Please include:
* Vimspector log (~/.vimspector.log): None generated
* Output from any or all UI diagnostic tabs (Server, etc.): Didn't get that far

**Environemnt**

* Version of Vimspector: 9f57cb0042e3aae9550efa2cd40163d74800f7e2

* Output of `vim --version` or `nvim --version`
$HOME is used as a placeholder for my home directory.
```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jul 22 2020 23:16:33)
Included patches: 1-1250
Compiled by Homebrew
Huge version without GUI.  Features included (+) or not (-):
+acl               -farsi             +mouse_sgr         +tag_binary
+arabic            +file_in_path      -mouse_sysmouse    -tag_old_static
+autocmd           +find_in_path      +mouse_urxvt       -tag_any_white
+autochdir         +float             +mouse_xterm       -tcl
-autoservername    +folding           +multi_byte        +termguicolors
-balloon_eval      -footer            +multi_lang        +terminal
+balloon_eval_term +fork()            -mzscheme          +terminfo
-browse            +gettext           +netbeans_intg     +termresponse
++builtin_terms    -hangul_input      +num64             +textobjects
+byte_offset       +iconv             +packages          +textprop
+channel           +insert_expand     +path_extra        +timers
+cindent           +ipv6              +perl              +title
-clientserver      +job               +persistent_undo   -toolbar
-clipboard         +jumplist          +popupwin          +user_commands
+cmdline_compl     +keymap            +postscript        +vartabs
+cmdline_hist      +lambda            +printer           +vertsplit
+cmdline_info      +langmap           +profile           +virtualedit
+comments          +libcall           -python            +visual
+conceal           +linebreak         +python3           +visualextra
+cryptv            +lispindent        +quickfix          +viminfo
+cscope            +listcmds          +reltime           +vreplace
+cursorbind        +localmap          +rightleft         +wildignore
+cursorshape       -lua               +ruby              +wildmenu
+dialog_con        +menu              +scrollbind        +windows
+diff              +mksession         +signs             +writebackup
+digraphs          +modify_fname      +smartindent       -X11
-dnd               +mouse             -sound             -xfontset
-ebcdic            -mouseshape        +spell             -xim
+emacs_tags        +mouse_dec         +startuptime       -xpm
+eval              -mouse_gpm         +statusline        -xsmp
+ex_extra          -mouse_jsbterm     -sun_workshop      -xterm_clipboard
+extra_search      +mouse_netterm     +syntax            -xterm_save
   system vimrc file: "$VIM/vimrc"
    │user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
    │ user exrc file: "$HOME/.exrc"
    │  defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "$HOME/.linuxbrew/share/vim"
Compilation: gcc-5 -c -I. -Iproto -DHAVE_CONFIG_H     -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc-5   -L. -fstack-protector-strong -rdynamic -Wl,-export-dynamic -L$HOME/.linuxbrew/opt/libyaml/lib  -Wl,-rpath,$HOME/.linuxbrew/opt/libyaml/lib -L$HOME/.linuxbrew/opt/openssl@1.1/lib  -Wl,-rpath,$HOME/.linuxbrew/opt/openssl@1.1/lib -L$HOME/.linuxbrew/opt/readline/lib
 -Wl,-rpath,$HOME/.linuxbrew/opt/readline/lib -Wl,-E -Wl,-rpath,$HOME/.linuxbrew/Cellar/perl/5.32.0/lib/perl5/5.32.0/x86_64-linux-thread-multi/CORE   -L/usr/local/lib -Wl,--as-needed -o vim        -lm -lelf  -lselinux  -lncurses -ldl   -Wl,-E -Wl,-rpath,$HOME/.linuxbrew/Cellar/perl/5.32.0/lib/perl5/5.32.0/x86_64-linux-thread-multi/CORE  -fstack-protector-strong -L/usr/local/lib  -L$HOME/.linuxbrew/Cellar/perl/5.32.0/lib/perl5/5.32.0/x86_64-linux-thread-multi/CORE -lperl -lpthread -lnsl -ldl -lm -lcrypt -lutil -lc  -L$HOME/.linuxbrew/opt/python@3.8/lib/python3.8/config-3.8-x86_64-linux-gnu -lpython3.8 -lcrypt -lpthread -ldl -lutil -lm -lm  -Wl,-rpath,$HOME/.linuxbrew/Cellar/ruby/2.7.1_3/lib -L$HOME/.linuxbrew/Cellar/ruby/2.7.1_3/lib -lruby -lm
```

* Output of `which vim` or `which nvim`:
```
$HOME/.linuxbrew/bin/vim
```

* Output of `:py3 print( __import__( 'sys' ).version )`:
```
3.8.5 (default, Jul 22 2020, 23:15:33)
[GCC 5.5.0]
```

* Output of `:py3 import vim`: No output or errors

* Output of `:py3 import vimspector`: No output or errors

* For neovim: output of `:checkhealth`: Not Applicable

* Operating system: Ubuntu 20.04 LTS

**Comment by harshasrisri** [comment]
I tried the same procedure on macOS Mojave 10.14.6 and it worked as expected.

**Comment by puremourning** [comment]
If you run vim as `vim -Nu NONE` then `:py3 import subprocess`, what is the output ?

**Comment by harshasrisri** [comment]
This is what I get:
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/subprocess.py", line 64, in <module>
    import msvcrt
ModuleNotFoundError: No module named 'msvcrt'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.8/subprocess.py", line 69, in <module>
    import _posixsubprocess
ModuleNotFoundError: No module named '_posixsubprocess'
Press ENTER or type command to continue
```

**Comment by puremourning** [comment]
yeah, you need to fix your vim and/or python. this is not a vimspector issue, it's a vim and/or python installation issue.

I can probably help debug it, but not using the issue tracker. Better to find me on Gitter.

> import msvcrt

That sounds windows only, what OS are you on?

>import subprocess

When this works in your REPL, check that the output of subprocess.__name__ is as expected (e.g. you don't have some weird global python module named `subprocess` which is not the standard library one) 

> ModuleNotFoundError: No module named '_posixsubprocess'

Try googling this error.

**Comment by harshasrisri** [comment]
I believe that vim installed with linuxbrew was using system's default python3 in this case. Putting linuxbrew earlier in the PATH resolved this issue.
