### ISSUE TITLE
Conditional Breakpoint doesn't crashes.

### ISSUE THREAD

**Issue by TornaxO7** [puremourning/vimspector#246]
> DO NOT DELETE THIS TEMPLATE. IF YOU DELETE THIS TEMPLATE AND DO NOT COMPLETE IT, YOUR ISSUE WILL BE CLOSED.

### Describe the bug

I'm trying to add an conditional breakpoint to a sample code but if I launch vimpsector, than an error pops up. Here's a gif:
![GIF](https://user-images.githubusercontent.com/50843046/91911351-2dcd0980-ecb1-11ea-98ba-047282829616.gif)

### Minimal reproduciton

> Please answer the following questions

* Does your issue reproduce using `vim -Nu /path/to/vimspector/support/minimal_vimrc` ?
Half. When using the same commands and file, I'm stuck in this:
![image](https://user-images.githubusercontent.com/50843046/91911865-3c67f080-ecb2-11ea-97ff-136bde5776aa.png)

* If you are using Neovim, does your issue reproduce using Vim
Yes

> List of steps to reproduce:

1. Run `vim -Nu /path/to/vimspector/support/minimal_vimrc rofl.c`
Content of `rofl.c`:
```c
#include <limits.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#ifndef NULL
    #define NULL ((void *) 0)
#endif

int main() {

    unsigned short counter = 0;

    while (counter <= 100)
        counter++;

    return EXIT_SUCCESS;
}
```

3. Go to the `counter++` line (it should be 15).
Call these functions:
```
:call vimspector#ToggleBreakpoint([{'condition' : 'counter == 10'}])
:call vimspector#Launch()
```

> Use the following Vimspector config file:

```json
{
  "configurations": {
    "my_profile": {
      "adapter": "vscode-cpptools",
      "configuration": {
        "request": "launch",
        "program": "./a.out",
        "args": ["-g", "*${CommandLineArgs}"],
        "setupCommands": [
          {
            "description": "Enable pretty-printing for gdb",
            "text": "-enable-pretty-printing",
            "ignoreFailures": true
          }
        ]
      }
    }
  }
}

```

### Expected behaviour

I expected that it works like the normal breakpoint but with an condition.

### Actual behaviour
I'm getting this error message:
![image](https://user-images.githubusercontent.com/50843046/91912424-62da5b80-ecb3-11ea-82fa-e50e71e821d7.png)
as text:
```python
Error detected while processing function <SNR>163__OnEvent[11]..provider#python3#Call:
line   18:
Error invoking 'python_execute' on channel 4 (python3-script-host):
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/tornax/.vim/plugged/vimspector/python3/vimspector/debug_session.py", line 359, in OnChannelData
    self._connection.OnData( data )
  File "/home/tornax/.vim/plugged/vimspector/python3/vimspector/debug_adapter_connection.py", line 158, in OnData
    self._ReadBody()
  File "/home/tornax/.vim/plugged/vimspector/python3/vimspector/debug_adapter_connection.py", line 232, in _ReadBody
    self._OnMessageReceived( message )
  File "/home/tornax/.vim/plugged/vimspector/python3/vimspector/debug_adapter_connection.py", line 276, in _OnMessageReceived
    getattr( self._handler, method )( message )
  File "/home/tornax/.vim/plugged/vimspector/python3/vimspector/debug_session.py", line 1014, in OnEvent_initialized
    self._breakpoints.SendBreakpoints( onBreakpointsDone )
  File "/home/tornax/.vim/plugged/vimspector/python3/vimspector/breakpoints.py", line 260, in SendBreakpoints
    dap_bp.update( bp[ 'options' ] )
ValueError: dictionary update sequence element #0 has length 1; 2 is required
Press ENTER or type command to continue
```

> What actually happened, including output, log files etc.
`vimspector.log`:
```log
2020-09-02 00:27:52,687 - INFO - **** INITIALISING NEW VIMSPECTOR SESSION ****
2020-09-02 00:27:52,687 - INFO - API is: neo
2020-09-02 00:27:52,687 - INFO - VIMSPECTOR_HOME = /home/tornax/.vim/plugged/vimspector
2020-09-02 00:27:52,689 - INFO - gadgetDir = /home/tornax/.vim/plugged/vimspector/gadgets/linux
2020-09-02 00:27:52,692 - DEBUG - Toggle found bp at /home/tornax/rofl.c:15 ? False (New)
2020-09-02 00:27:53,880 - INFO - User requested start debug session with {}
2020-09-02 00:27:53,881 - DEBUG - Reading gadget config: /home/tornax/.vim/plugged/vimspector/gadgets/linux/.gadgets.json
2020-09-02 00:27:53,883 - DEBUG - Reading gadget config: None
2020-09-02 00:27:53,883 - DEBUG - Reading configurations from: None
2020-09-02 00:27:53,883 - DEBUG - Reading configurations from: /home/tornax/.vimspector.json
2020-09-02 00:27:54,765 - DEBUG - Value for CommandLineArgs not set in ${CommandLineArgs} (from ${CommandLineArgs}): set to 
2020-09-02 00:27:54,766 - INFO - Configuration: {"adapter": "vscode-cpptools", "configuration": {"request": "launch", "program": "./a.out", "args": ["-g"], "setupCommands": [{"description": "Enable pretty-printing for gdb", "text": "-enable-pretty-printing", "ignoreFailures": true}]}}
2020-09-02 00:27:54,766 - INFO - Adapter: {"attach": {"pidProperty": "processId", "pidSelect": "ask"}, "command": ["/home/tornax/.vim/plugged/vimspector/gadgets/linux/vscode-cpptools/debugAdapters/OpenDebugAD7"], "configuration": {"args": [], "cwd": "/home/tornax", "environment": [], "type": "cppdbg"}, "name": "cppdbg"}
2020-09-02 00:27:55,087 - INFO - Starting debug adapter with: {"attach": {"pidProperty": "processId", "pidSelect": "ask"}, "command": ["/home/tornax/.vim/plugged/vimspector/gadgets/linux/vscode-cpptools/debugAdapters/OpenDebugAD7"], "configuration": {"args": [], "cwd": "/home/tornax", "environment": [], "type": "cppdbg"}, "name": "cppdbg"}
2020-09-02 00:27:55,089 - INFO - Debug Adapter Started
2020-09-02 00:27:55,090 - DEBUG - Sending Message: {"command": "initialize", "arguments": {"adapterID": "cppdbg", "clientID": "vimspector", "clientName": "vimspector", "linesStartAt1": true, "columnsStartAt1": true, "locale": "en_GB", "pathFormat": "path", "supportsVariableType": true, "supportsVariablePaging": false, "supportsRunInTerminalRequest": true}, "seq": 0, "type": "request"}
2020-09-02 00:27:55,222 - INFO - Server stderr: waiting for v8 protocol on stdin/stdout

2020-09-02 00:27:55,619 - DEBUG - Message received: {'type': 'response', 'request_seq': 0, 'success': True, 'command': 'initialize', 'body': {'supportsConfigurationDoneRequest': True, 'supportsFunctionBreakpoints': True, 'supportsConditionalBreakpoints': True, 'supportsEvaluateForHovers': True, 'exceptionBreakpointFilters': [], 'supportsSetVariable': True, 'additionalModuleColumns': [], 'supportedChecksumAlgorithms': []}, 'seq': 1}
2020-09-02 00:27:55,619 - DEBUG - LAUNCH!
2020-09-02 00:27:55,620 - DEBUG - Sending Message: {"command": "launch", "arguments": {"args": ["-g"], "cwd": "/home/tornax", "environment": [], "type": "cppdbg", "request": "launch", "program": "./a.out", "setupCommands": [{"description": "Enable pretty-printing for gdb", "text": "-enable-pretty-printing", "ignoreFailures": true}], "name": "test"}, "seq": 1, "type": "request"}
2020-09-02 00:27:55,783 - DEBUG - Message received: {'type': 'request', 'command': 'runInTerminal', 'arguments': {'kind': 'integrated', 'title': 'cppdbg: a.out', 'cwd': '', 'args': ['/bin/sh', '/tmp/Microsoft-MIEngine-Cmd-qmurx7d6.h6o'], 'env': {}}, 'seq': 2}
2020-09-02 00:27:55,783 - DEBUG - Defaulting working directory to /home/tornax
2020-09-02 00:27:55,900 - DEBUG - Sending Message: {"seq": 2, "type": "response", "request_seq": 2, "command": "runInTerminal", "body": {"processId": 591412}, "success": true}
2020-09-02 00:27:56,012 - DEBUG - Message received: {'type': 'event', 'event': 'output', 'body': {'category': 'telemetry', 'output': 'VS/Diagnostics/Debugger/Launch', 'data': {'VS.Diagnostics.Debugger.ImplementationName': 'Microsoft.MIDebugEngine', 'VS.Diagnostics.Debugger.EngineVersion': '16.5.10325.1', 'VS.Diagnostics.Debugger.HostVersion': '16.5.10325.1', 'VS.Diagnostics.Debugger.AdapterId': 'cppdbg', 'VS.Diagnostics.Debugger.Launch.Duration': 365, 'VS.Diagnostics.Debugger.Launch.IsCoreDump': False, 'VS.Diagnostics.Debugger.VisualizerFileUsed': False, 'VS.Diagnostics.Debugger.SourceFileMappings': 0, 'VS.Diagnostics.Debugger.MIMode': None}}, 'seq': 3}
2020-09-02 00:27:56,058 - DEBUG - Message received: {'type': 'response', 'request_seq': 1, 'success': True, 'command': 'launch', 'body': {}, 'seq': 4}
2020-09-02 00:27:56,059 - DEBUG - Message received: {'type': 'event', 'event': 'initialized', 'body': {}, 'seq': 5}
2020-09-02 00:27:59,624 - DEBUG - Stop debug adapter with callback : self._Reset()
2020-09-02 00:27:59,625 - DEBUG - Sending Message: {"command": "disconnect", "arguments": {}, "seq": 3, "type": "request"}
2020-09-02 00:27:59,638 - DEBUG - Message received: {'type': 'event', 'event': 'output', 'body': {'category': 'stdout', 'output': '=thread-group-added,id="i1"\nGNU gdb (GDB) 9.2\nCopyright (C) 2020 Free Software Foundation, Inc.\nLicense GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>\nThis is free software: you are free to change and redistribute it.\nThere is NO WARRANTY, to the extent permitted by law.\nType "show copying" and "show warranty" for details.\nThis GDB was configured as "x86_64-pc-linux-gnu".\nType "show configuration" for configuration details.\nFor bug reporting instructions, please see:\n<http://www.gnu.org/software/gdb/bugs/>.\nFind the GDB manual and other documentation resources online at:\n    <http://www.gnu.org/software/gdb/documentation/>.\n\nFor help, type "help".\nType "apropos word" to search for commands related to "word".\nWarning: Debuggee TargetArchitecture not detected, assuming x86_64.\n=cmd-param-changed,param="pagination",value="off"\n'}, 'seq': 6}
2020-09-02 00:27:59,656 - DEBUG - Message received: {'type': 'event', 'event': 'output', 'body': {'category': 'stdout', 'output': 'Stopped due to shared library event (no libraries added or removed)\n'}, 'seq': 7}
2020-09-02 00:27:59,665 - DEBUG - Message received: {'type': 'event', 'event': 'output', 'body': {'category': 'console', 'output': "The program './a.out' has exited with code 42 (0x0000002a).\r\n\n"}, 'seq': 8}
2020-09-02 00:27:59,668 - DEBUG - Message received: {'type': 'event', 'event': 'output', 'body': {'category': 'telemetry', 'output': 'VS/Diagnostics/Debugger/DebugCompleted', 'data': {'VS.Diagnostics.Debugger.ImplementationName': 'Microsoft.MIDebugEngine', 'VS.Diagnostics.Debugger.EngineVersion': '16.5.10325.1', 'VS.Diagnostics.Debugger.HostVersion': '16.5.10325.1', 'VS.Diagnostics.Debugger.AdapterId': 'cppdbg', 'VS.Diagnostics.Debugger.DebugCompleted.BreakCounter': 0}}, 'seq': 9}
2020-09-02 00:27:59,715 - INFO - Server stderr: 
2020-09-02 00:27:59,757 - DEBUG - Message received: {'type': 'response', 'request_seq': 3, 'success': True, 'command': 'disconnect', 'body': {}, 'seq': 10}
2020-09-02 00:27:59,757 - DEBUG - Setting server exit handler before disconnect
2020-09-02 00:27:59,771 - INFO - The server has terminated with status 0
2020-09-02 00:27:59,774 - DEBUG - Running server exit handler
2020-09-02 00:27:59,774 - INFO - Debugging complete.
2020-09-02 00:27:59,774 - DEBUG - Clearing down UI
```

> Please include:
> * Vimspector log (~/.vimspector.log)
> * Output from any or all UI diagnostic tabs (Server, etc.)

### Environemnt

***NOTE***: NeoVim is supported only on a best-effort basis. Please check the README
for limitations of neovim. Don't be offended if I ask you to reproduce issues in
Vim.

***NOTE***: Windows support is experimental and best-efrort only. If you find an
issue related to Windows or windows-isms, consider sending a PR or
discussing on Gitter rather than raising an issue.

* Version of Vimspector: (e.g. output of `git rev-parse HEAD` if cloned or the
  name of the tarball used to install otherwise)

Vimspector version (downloaded with vim-plug):
```
e81be848a112350656e7c273777185c3c1a88e3e
```

* Output of `vim --version` or `nvim --version`
```
NVIM v0.4.4
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.4.4/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

* Output of `which vim` or `which nvim`:

```
/usr/bin/nvim
```

* Output of `:py3 print( __import__( 'sys' ).version )`:
![image](https://user-images.githubusercontent.com/50843046/91913216-62db5b00-ecb5-11ea-8c45-d5dda77730db.png)

* Output of `:py3 import vim`:
(Nothing happened)
```
:py3 import vim
```

* Output of `:py3 import vimspector`:
(Nothing happened)
```
:py3 import vimspector
```

* For neovim: output of `:checkhealth`

```vim

health#coc#check
========================================================================
  - OK: Environment check passed

  - OK: Javascript bundle build/index.js found
  - OK: Service started

health#vimtex#check
========================================================================
## vimtex
  - OK: Vim version should have full support!
  - OK: General viewer should work properly!
  - WARNING: Compiler callbacks will not work!
    - ADVICE:
      - `neovim-remote` / `nvr` is required for callbacks to work with neovim
      - Please also set |g:vimtex_compiler_progname| = 'nvr'
      - For more info, see :help |vimtex-faq-neovim|

health#mkdp#check
========================================================================
  - INFO: Platform: linux
  - INFO: Nvim Version: NVIM v0.4.4
  - INFO: Node version: v14.9.0

  - INFO: Script: /home/tornax/.vim/plugged/markdown-preview.nvim/app/server.js
  - INFO: Script exists: 1
  - OK: Using node

health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: Release

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $COLORTERM='truecolor'

health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: xclip

## Python 2 provider (optional)
  - WARNING: No Python executable found that can `import neovim`. Using the first available executable for diagnostics.
  - ERROR: Python provider error:
    - ADVICE:
      - provider/pythonx: Could not load Python 2:
          python2 not found in search path or not executable.
          python2.7 not found in search path or not executable.
          python2.6 not found in search path or not executable.
          /usr/bin/python is Python 3.8 and cannot provide Python 2.
  - INFO: Executable: Not found

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Executable: /usr/bin/python3
  - INFO: Python version: 3.8.5
  - INFO: pynvim version: 0.4.1
  - OK: Latest pynvim is installed.

## Ruby provider (optional)
  - INFO: Ruby: ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux]
  - WARNING: `neovim-ruby-host` not found.
    - ADVICE:
      - Run `gem install neovim` to ensure the neovim RubyGem is installed.
      - Run `gem environment` to ensure the gem bin directory is in $PATH.
      - If you are using rvm/rbenv/chruby, try "rehashing".
      - See :help |g:ruby_host_prog| for non-standard gem installations.

## Node.js provider (optional)
  - INFO: Node.js: v14.9.0
  - INFO: Neovim node.js host: /usr/lib/node_modules/neovim/bin/cli.js
  - OK: Latest "neovim" npm/yarn package is installed: 4.9.0


```

* Operating system: <linux or macOS> and version
  
Output of `uname -r`:
```
5.8.5-arch1-1
```
OS: Arch Linux

> Please complete the following declaration. If this declaration is not completed, your issue may be closed without comment.

* I have read and understood [CONTRIBUTING.md](https://github.com/puremourning/vimspector/blob/master/CONTRIBUTING.md) \[Yes/No]

### Additional information
None

**Comment by puremourning** [comment]
You’re passing a list to the ToggleBreakpoint function. You need to pass a dict. 

```
:call vimspector#ToggleBreakpoint( { ‘condition’: ‘counter == 10’ } )
```

**Comment by TornaxO7** [comment]
Oh ok. Haha such a simple mistake xD I've created a veeeeeeery small pull request which removed the square brackets of this call:
![image](https://user-images.githubusercontent.com/50843046/91964478-74e9e780-ed0f-11ea-90bc-282949c5868a.png)
That was the reason why I added the square bracktes.
