### ISSUE TITLE
vim.error: Vim(sign):E239: Invalid sign text: ●▶

### ISSUE THREAD

**Issue by tamago324** [puremourning/vimspector#263]
An error similar to #233 occurred.

The error message is as follows

```
Error detected while processing function vimspector#Continue:
line    4:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\tamago324\vimfiles\plugged\vimspector\python3\vimspector\debug_session.py", line 452, in Continue
    self.Start()
  File "C:\Users\tamago324\vimfiles\plugged\vimspector\python3\vimspector\debug_session.py", line 268, in Start
    self._StartWithConfiguration( configuration, adapter )
  File "C:\Users\tamago324\vimfiles\plugged\vimspector\python3\vimspector\debug_session.py", line 313, in _StartWithConfiguration
    start()
  File "C:\Users\tamago324\vimfiles\plugged\vimspector\python3\vimspector\debug_session.py", line 281, in start
    self._SetUpUI()
  File "C:\Users\tamago324\vimfiles\plugged\vimspector\python3\vimspector\debug_session.py", line 566, in _SetUpUI
    self._codeView = code.CodeView( code_window, self._api_prefix )
  File "C:\Users\tamago324\vimfiles\plugged\vimspector\python3\vimspector\code.py", line 60, in __init__
    signs.DefineSign( 'vimspectorPCBP',
  File "C:\Users\tamago324\vimfiles\plugged\vimspector\python3\vimspector\signs.py", line 26, in DefineSign
    vim.command( cmd )
vim.error: Vim(sign):E239: Invalid sign text: ●▶
```

Maybe it needs to be a single character, like vimspectorPCBP.

In my environment, it looked like this
![image](https://user-images.githubusercontent.com/16581287/94283116-92ffdc00-ff8b-11ea-97cc-f9386c4a8dcc.png)

Thank you!

**Comment by puremourning** [comment]
Please complete the issue template. See CONTRIBUTING.md.

**Comment by tamago324** [comment]
I'm sorry.
I omitted it.
I will add it later 🙇‍♂️

**Comment by puremourning** [comment]
TBH I think this is a Neovim-specific thing.

You'll have to use the GUI customisation to set a single-character for the sign (`sign define vimspectorPCBP text=X ...`) in your vimrc.

**Comment by puremourning** [comment]
https://github.com/puremourning/vimspector#changing-the-default-signs

**Comment by puremourning** [comment]
hmm actually, it's not Neovim. so I'm confused. will need those steps to repro and diagnostics, but yeah it could be the ambiwidth thing again, in which case you can pick another one with a custom sign definition. I guess vimspector could check the value of ambiwidth and fall back to another sign in that case, e.g. 

```python
if vim.options[ 'ambiwidth' ] == 'double':
  # use a single character... but which one?
else:
  # use what we have
```

**Comment by puremourning** [comment]
yeah I can repro.

vim -Nu minimal_vimrc --cmd 'set ambiwidth=double'

**Comment by tamago324** [comment]
Yes. I think it's a problem with ambiwidth, probably.

**Comment by tamago324** [comment]
I will try to write a better description of how to reproduce it next time.

Sorry.

**Comment by puremourning** [comment]
no worries, I'll fix this and add a regression test so I don't break you again!

**Comment by tamago324** [comment]
Thank you 😆
