### ISSUE TITLE
Error invoking 'python_execute' self._breakpoints TypeError: string indices must be integers

### ISSUE THREAD

**Issue by ivan-volnov** [puremourning/vimspector#278]
### Describe the bug

```
Error invoking 'python_execute' on channel 4 (python3-script-host):
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/user/.local/share/nvim/plugged/vimspector/python3/vimspector/debug_session.py", line 361, in OnChannelDa
ta
    self._connection.OnData( data )
  File "/Users/user/.local/share/nvim/plugged/vimspector/python3/vimspector/debug_adapter_connection.py", line 158, in
OnData
    self._ReadBody()
  File "/Users/user/.local/share/nvim/plugged/vimspector/python3/vimspector/debug_adapter_connection.py", line 232, in
_ReadBody
    self._OnMessageReceived( message )
  File "/Users/user/.local/share/nvim/plugged/vimspector/python3/vimspector/debug_adapter_connection.py", line 276, in
_OnMessageReceived
    getattr( self._handler, method )( message )
  File "/Users/user/.local/share/nvim/plugged/vimspector/python3/vimspector/debug_session.py", line 1053, in OnEvent_br
eakpoint
    self._codeView.AddBreakpoints( None, bp )
  File "/Users/user/.local/share/nvim/plugged/vimspector/python3/vimspector/code.py", line 177, in AddBreakpoints
    self._breakpoints[ breakpoint[ 'source' ][ 'path' ] ].append(
TypeError: string indices must be integers
Press ENTER or type command to continue
```

### Minimal reproduciton

Does your issue reproduce using vim -Nu /path/to/vimspector/support/minimal_vimrc ? Yes
If you are using Neovim, does your issue reproduce using Vim? Yes

> Please answer the following questions

> List of steps to reproduce:

> 1. set a breakpoint
> 2. :call vimspector#Launch()

> Use the following Vimspector config file:

```
{
    "configurations": {
        "Debug": {
            "adapter": "lldb-vscode",
            "configuration": {
                "request": "launch",
                "program": "${workspaceRoot}/Debug/main",
                "cwd": "${workspaceRoot}/Debug",
                "externalConsole": false,
                "MIMode": "lldb"
            }
        }
    },
    "adapters": {
        "lldb-vscode": {
            "variables": {
                "LLVM": {
                    "shell": "brew --prefix llvm"
                }
            },
            "attach": {
                "pidProperty": "pid",
                "pidSelect": "ask"
            },
            "command": [
                "${LLVM}/bin/lldb-vscode"
            ],
            "env": {
                "LLDB_LAUNCH_FLAG_LAUNCH_IN_TTY": "YES"
            },
            "name": "lldb"
        }
    }
}
```

### Expected behaviour

> Provide A clear and concise description of what you expected to happen.

### Actual behaviour

> What actually happened, including output, log files etc.

> Please include:
> * Vimspector log (~/.vimspector.log)
> * Output from any or all UI diagnostic tabs (Server, etc.)

### Environemnt

* Version of Vimspector: f6726de058ca3d1aa2f739c5cca98bef9904152e

* Output of `vim --version` or `nvim --version`

```
NVIM v0.4.4
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20200808-89283-1us0ytm/neovim-0.4.4/build/config -I/tmp/neovim-20200808-89283-1us0ytm/neovim-0.4.4/src -I/usr/local/include -I/tmp/neovim-20200808-89283-1us0ytm/neovim-0.4.4/deps-build/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include -I/usr/local/opt/gettext/include -I/tmp/neovim-20200808-89283-1us0ytm/neovim-0.4.4/build/src/nvim/auto -I/tmp/neovim-20200808-89283-1us0ytm/neovim-0.4.4/build/include
Compiled by brew@Catalina

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.4.4/share/nvim"

Run :checkhealth for more info
```

* Output of `which vim` or `which nvim`:

```
/usr/local/bin/nvim
```

* Output of `:py3 print( __import__( 'sys' ).version )`:

```
3.8.5 (default, Jul 21 2020, 10:48:26)
[Clang 11.0.3 (clang-1103.0.32.62)]
```

* Output of `:py3 import vim`:

```
none
```

* Output of `:py3 import vimspector`:

```
none
```

* For neovim: output of `:checkhealth`

```
health#coc#check
========================================================================
  - OK: Environment check passed

  - OK: Javascript bundle build/index.js found
  - OK: Service started

health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: Release

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $TERM_PROGRAM='iTerm.app'
  - INFO: $COLORTERM='truecolor'

health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: pbcopy

## Python 2 provider (optional)
  - WARNING: No Python executable found that can `import neovim`. Using the first available executable for diagnostics.
  - ERROR: Python provider error:
    - ADVICE:
      - provider/pythonx: Could not load Python 2:
          /usr/bin/python2 does not have the "neovim" module. :help |provider-python|
          /usr/bin/python2.7 does not have the "neovim" module. :help |provider-python|
          python2.6 not found in search path or not executable.
          /usr/bin/python does not have the "neovim" module. :help |provider-python|
  - INFO: Executable: Not found

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Multiple python3 executables found.  Set `g:python3_host_prog` to avoid surprises.
  - INFO: Executable: /usr/local/bin/python3
  - INFO: Other python executable: /usr/bin/python3
  - INFO: Python version: 3.8.5
  - INFO: pynvim version: 0.4.2
  - OK: Latest pynvim is installed.

## Ruby provider (optional)
  - INFO: Ruby: ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
  - WARNING: `neovim-ruby-host` not found.
    - ADVICE:
      - Run `gem install neovim` to ensure the neovim RubyGem is installed.
      - Run `gem environment` to ensure the gem bin directory is in $PATH.
      - If you are using rvm/rbenv/chruby, try "rehashing".
      - See :help |g:ruby_host_prog| for non-standard gem installations.

## Node.js provider (optional)
  - INFO: Node.js: v14.13.0
  - INFO: Neovim node.js host: /usr/local/lib/node_modules/neovim/bin/cli.js
  - WARNING: Package "neovim" is out-of-date. Installed: 4.5.0, latest: 4.9.0
    - ADVICE:
      - Run in shell: npm install -g neovim
      - Run in shell (if you use yarn): yarn global add neovim
```

* Operating system: macOs Catalina 10.15.7
  
### Declaration

> Please complete the following declaration. If this declaration is not completed, your issue may be closed without comment.

* I have read and understood [CONTRIBUTING.md](https://github.com/puremourning/vimspector/blob/master/CONTRIBUTING.md) \Yes

**Comment by puremourning** [comment]
Please do not omit sections from the issue template:

Please answer the following questions
Does your issue reproduce using vim -Nu /path/to/vimspector/support/minimal_vimrc ? [Yes/No]
If you are using Neovim, does your issue reproduce using Vim? [Yes/No]

**Comment by puremourning** [comment]
I can't reproduce. Can you provide step-by-step reproduction instructions using the code in `/path/to/vimspector/tests/testdata/cpp/simple` ?

**Comment by ivan-volnov** [comment]
> Please do not omit sections from the issue template:
fixed

Yes, it reproduces using vim and also with minimal_vimrc

**Comment by puremourning** [comment]
I can't reproduce it though, even using your config above, so need more explicit steps.

For example, you don't even set any breakpoints in the repro case, so I don't understand what could be calling that code. You also didn't include the vimspector log (as was requested in the issue template).

If I can't repro, I can't fix it. It's that simple.

**Comment by ivan-volnov** [comment]
> For example, you don't even set any breakpoints in the repro case, so I don't understand what could be calling that code. 

Oh, actually I did. Sorry. Updated the issue description

**Comment by puremourning** [comment]
I still can't reproduce and you still didn't include the log file...

**Comment by puremourning** [comment]
> Can you provide step-by-step reproduction instructions using the code in /path/to/vimspector/tests/testdata/cpp/simple using the minimal vimrc.

**Comment by ivan-volnov** [comment]
@puremourning please have a look at the screen recording:
https://www.dropbox.com/s/v3by68horwv5e0l/Screen%20Recording%202020-10-10%20at%209.27.20%20PM.mov?dl=0

**Comment by ivan-volnov** [comment]
Just installed a fresh vim special for testing purposes.

```
/usr/local/bin/vim --version
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Oct  7 2020 23:36:35)
macOS version
Included patches: 1-1800
Compiled by Homebrew
Huge version without GUI.  Features included (+) or not (-):
+acl               -farsi             +mouse_sgr         +tag_binary
+arabic            +file_in_path      -mouse_sysmouse    -tag_old_static
+autocmd           +find_in_path      +mouse_urxvt       -tag_any_white
+autochdir         +float             +mouse_xterm       -tcl
-autoservername    +folding           +multi_byte        +termguicolors
-balloon_eval      -footer            +multi_lang        +terminal
+balloon_eval_term +fork()            -mzscheme          +terminfo
-browse            +gettext           +netbeans_intg     +termresponse
++builtin_terms    -hangul_input      +num64             +textobjects
+byte_offset       +iconv             +packages          +textprop
+channel           +insert_expand     +path_extra        +timers
+cindent           +ipv6              +perl              +title
-clientserver      +job               +persistent_undo   -toolbar
+clipboard         +jumplist          +popupwin          +user_commands
+cmdline_compl     +keymap            +postscript        +vartabs
+cmdline_hist      +lambda            +printer           +vertsplit
+cmdline_info      +langmap           +profile           +virtualedit
+comments          +libcall           -python            +visual
+conceal           +linebreak         +python3           +visualextra
+cryptv            +lispindent        +quickfix          +viminfo
+cscope            +listcmds          +reltime           +vreplace
+cursorbind        +localmap          +rightleft         +wildignore
+cursorshape       +lua               +ruby              +wildmenu
+dialog_con        +menu              +scrollbind        +windows
+diff              +mksession         +signs             +writebackup
+digraphs          +modify_fname      +smartindent       -X11
-dnd               +mouse             -sound             -xfontset
-ebcdic            -mouseshape        +spell             -xim
+emacs_tags        +mouse_dec         +startuptime       -xpm
+eval              -mouse_gpm         +statusline        -xsmp
+ex_extra          -mouse_jsbterm     -sun_workshop      -xterm_clipboard
+extra_search      +mouse_netterm     +syntax            -xterm_save
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H   -DMACOS_X -DMACOS_X_DARWIN  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: clang   -L. -fstack-protector-strong -L/usr/local/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl@1.1/lib -L/usr/local/opt/readline/lib  -L/usr/local/lib -o vim        -lncurses -liconv -lintl -framework AppKit  -L/usr/local/opt/lua/lib -llua5.3 -mmacosx-version-min=10.15 -fstack-protector-strong -L/usr/local/lib  -L/usr/local/Cellar/perl/5.32.0/lib/perl5/5.32.0/darwin-thread-multi-2level/CORE -lperl -lm -lutil -lc  -L/usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/config-3.9-darwin -lpython3.9 -framework CoreFoundation  -lruby.2.7
```

**Comment by puremourning** [comment]
OK thanks, I can repro by answering "Y" to the exception-breakpoints questions.

**Comment by puremourning** [comment]
I pushed a PR, can you confirm it resolves for you ?

**Comment by ivan-volnov** [comment]
Yes, it's working now. Thank you.

**Comment by ivan-volnov** [comment]
By the way do you have any idea why it's trying to open a separate terminal window to run debugger? (see the video)

**Comment by puremourning** [comment]
> By the way do you have any idea why it's trying to open a separate terminal window to run debugger? (see the video)

Yes. https://github.com/puremourning/vimspector#faq

I _highly_ recommend CodeLLDB for macOS - it's great. 

You can switch with `:VimspectorInstall CodeLLDB` and then change your config to this:

```json
{
    "configurations": {
        "Debug": {
            "adapter": "CodeLLDB",
            "configuration": {
                "request": "launch",
                "program": "${workspaceRoot}/Debug/main",
                "cwd": "${workspaceRoot}/Debug",
                "expressions": "native",
            }
        }
    },
}
```
