### ISSUE TITLE
Unknown Function: bufadd

### ISSUE THREAD

**Issue by khurd21** [puremourning/vimspector#391]
> DO NOT DELETE THIS TEMPLATE. IF YOU DELETE THIS TEMPLATE AND DO NOT COMPLETE IT, YOUR ISSUE WILL BE CLOSED.

### Describe the bug

> Provide A clear and concise description of what the bug is.

When I press F5 to enter the debugging, I receive an error message with the following: 
```
/.vim/bundle/vimspector/python3/vimspector/utils.py", line 63, in NewEmptyBuffer
    bufnr = int( vim.eval( 'bufadd("")' ) )
vim.error: Vim:E117: Unknown function: bufadd
```

Tested the same code on MacOS and works fine. However I am getting the above error on Raspbian.

### Minimal reproduciton

> Please answer the following questions

* Does your issue reproduce using `vim --clean -Nu /path/to/vimspector/support/minimal_vimrc` ? 
      Yes
* If you are using Neovim, does your issue reproduce using Vim?
       I am not running NeoVim.

> List of steps to reproduce:

> 1. Made a simple main.cpp file saying hello world.
> 2. g++ -g main.cpp
> 3. vim main.cpp, I am able to set line breaks with F5
> 4. Press F9 to enter the debug mode, error message is displayed.

This above example with the same vimspector.json [changed MIMode to lldb] works on Mac, does not work when I try to move it to Raspbian.

> Use the following Vimspector config file:

```
{
    "configurations" : {       
        "Launch" : {           
            "adapter" : "vscode-cpptools",  
            "configuration" : {
                "request" : "launch",           
                "program" : "a.out",            
                "cwd" : "/${workspaceRoot}",    
                "externalConsole" : true,       
                "MIMode" : "gdb"               
            }                  
        }
    }
}
```

### Expected behaviour

> Provide A clear and concise description of what you expected to happen.

Enter debug mode

### Actual behaviour

> What actually happened, including output, log files etc.

It crashes. He is the error message in full:

```
Error detected while processing function vimspector#Continue:                                                
line    4:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/pi/.vim/bundle/vimspector/python3/vimspector/debug_session.py", line 485, in Continue
    self.Start()
  File "/home/pi/.vim/bundle/vimspector/python3/vimspector/debug_session.py", line 285, in Start
    self._StartWithConfiguration( configuration, adapter )
  File "/home/pi/.vim/bundle/vimspector/python3/vimspector/debug_session.py", line 332, in _StartWithConfiguration
    start()
  File "/home/pi/.vim/bundle/vimspector/python3/vimspector/debug_session.py", line 299, in start
    self._SetUpUI()
  File "/home/pi/.vim/bundle/vimspector/python3/vimspector/debug_session.py", line 705, in _SetUpUI
    self._SetUpUIVertical()
  File "/home/pi/.vim/bundle/vimspector/python3/vimspector/debug_session.py", line 805, in _SetUpUIVertical
    self._api_prefix )
  File "/home/pi/.vim/bundle/vimspector/python3/vimspector/output.py", line 259, in __init__
    self._CreateBuffer( b )
  File "/home/pi/.vim/bundle/vimspector/python3/vimspector/output.py", line 191, in _CreateBuffer
    tab_buffer = TabBuffer( utils.NewEmptyBuffer(), len( self._buffers ) )
  File "/home/pi/.vim/bundle/vimspector/python3/vimspector/utils.py", line 63, in NewEmptyBuffer
    bufnr = int( vim.eval( 'bufadd("")' ) )
vim.error: Vim:E117: Unknown function: bufadd
Press ENTER or type command to continue
```

> Please include:
> * Vimspector log (~/.vimspector.log)
```
2021-04-28 23:17:46,191 - INFO - **** INITIALISING NEW VIMSPECTOR SESSION ****
2021-04-28 23:17:46,191 - INFO - API is:
2021-04-28 23:17:46,191 - INFO - VIMSPECTOR_HOME = /home/pi/.vim/bundle/vimspector
2021-04-28 23:17:46,213 - INFO - gadgetDir = /home/pi/.vim/bundle/vimspector/gadgets/linux
2021-04-28 23:17:48,734 - INFO - User requested start debug session with {}
2021-04-28 23:17:48,739 - DEBUG - Reading configurations from: None
2021-04-28 23:17:48,740 - DEBUG - Reading configurations from: /home/pi/Replicate_Problem/.vimspector.json
2021-04-28 23:17:48,746 - DEBUG - Reading gadget config: /home/pi/.vim/bundle/vimspector/gadgets/linux/.gadgets.json
2021-04-28 23:17:48,813 - DEBUG - Reading gadget config: None
2021-04-28 23:17:48,815 - INFO - Configuration: {"adapter": "vscode-cpptools", "configuration": {"request": "launch", "program": "a.out", "cwd": "//home/pi/Replicate_Problem", "externalConsole": true, "MIMode": "gdb"}}
2021-04-28 23:17:48,815 - INFO - Adapter: {"attach": {"pidProperty": "processId", "pidSelect": "ask"}, "command": ["/home/pi/.vim/bundle/vimspector/gadgets/linux/vscode-cpptools/debugAdapters/OpenDebugAD7"], "configuration": {"args": [], "cwd": "/home/pi/Replicate_Problem", "environment": [], "type": "cppdbg"}, "name": "cppdbg"}
2021-04-28 23:17:48,817 - DEBUG - min_width/height: 149/50, actual: 119/51 - result: vertical
```
> * Output from any or all UI diagnostic tabs (Server, etc.)

### Environemnt

Raspberry Pi running Raspbian

***NOTE***: NeoVim is supported only on a best-effort basis. Please check the README
for limitations of neovim. Don't be offended if I ask you to reproduce issues in
Vim.

***NOTE***: Windows support is experimental and best-efrort only. If you find an
issue related to Windows or windows-isms, consider sending a PR or
discussing on Gitter rather than raising an issue.

* Version of Vimspector: (e.g. output of `git rev-parse HEAD` if cloned or the
  name of the tarball used to install otherwise)

This is what was produced running the below command in vimspector directory:
```
git rev-parse HEAD
a47d0b921c42be740e57d75a73ae15a8ee0141d4
```

* Output of `vim --version` or `nvim --version`

```
VIM - Vi IMproved 8.1
```

* Output of `which vim` or `which nvim`:

```
/usr/bin/vim
```

* Output of `:py3 print( __import__( 'sys' ).version )`:

```
[GCC 8.3.0]
```

* Output of `:py3 import vim`:

```
Nothing popped up
```

* Output of `:py3 import vimspector`:

```
Nothing popped up
```

* For neovim: output of `:checkhealth`

```
I do not have nevoid
```

* Operating system: <linux or macOS> and version

```
Linux, Raspbian
```
  
### Declaration

> Please complete the following declaration. If this declaration is not completed, your issue may be closed without comment.

* I have read and understood [CONTRIBUTING.md](https://github.com/puremourning/vimspector/blob/master/CONTRIBUTING.md)
```
Yes
```

**Comment by puremourning** [comment]
https://github.com/puremourning/vimspector#dependencies

You need vim 8.2
