### ISSUE TITLE
Install chrome debugger

### ISSUE THREAD

**Issue by ladevieq** [puremourning/vimspector#65]
**Describe the bug**
When running install_gadget script with option `--force-enable-chrome`. Script print `install_gadget.py: error: unrecognized arguments: --force-enable-chrome`.

**To Reproduce**
Run install_gadget script with option `--force-enable-chrome`.

Vimspector config file:

```
{
  "adapters": {
      "lldb-mi": {
        "name": "lldb-mi",
        "command": [
          "node",
          "$HOME/.vscode/extensions/webfreak.debug-0.22.0/out/src/lldb.js"
        ]
      },
      "cppdbg": {
        "name": "cppdbg",
        "command": [ "$HOME/.vscode/extensions/ms-vscode.cpptools-0.20.1/debugAdapters/OpenDebugAD7" ],
        "attach": {
          "pidProperty": "processId",
          "pidSelect": "ask"
        }
      },
      "python": {
        "name": "python",
        "command": [
          "node",
          "$HOME/.vscode/extensions/ms-python.python-2018.4.0/out/client/debugger/Main.js"
        ]
      },
      "bashdb": {
        "name": "bashdb",
        "command": [
          "node",
          "$HOME/.vscode/extensions/rogalmic.bash-debug-0.2.0/out/bashDebug.js"
        ]
      },
      "lldb": {
        "name": "lldb",
        "command": [
          "lldb",
          "-b",
          "-O",
          "command script import '$HOME/.vscode/extensions/vadimcn.vscode-lldb-0.8.7/adapter'",
          "-O",
          "script adapter.main.run_stdio_session()"
        ]
      }
  },
  "configurations": {
    "simple_c_program - lldb-mi Launch": {
      "adapter": "lldb-mi",
      "configuration": {
        "request": "launch",
        "target": "support/test/cpp/simple_c_program/test",
        "args": [],
        "cwd": ".",
        "lldbmipath": "$HOME/.vscode/extensions/ms-vscode.cpptools-0.20.1/debugAdapters/lldb/bin/lldb-mi",
        "trace": true,
        "logFilePath": "$HOME/.vimspector.protocol.log"
      }
    },
    "simple_c_progra - ms Launch": {
      "adapter": "cppdbg",
      "configuration": {
        "name": "ms Launch",
        "type": "cppdbg",
        "request": "launch",
        "program": "${workspaceRoot}/support/test/cpp/simple_c_program/test",
        "args": [],
        "cwd": "$HOME",
        "environment": [],
        "externalConsole": true,
        "MIMode": "lldb"
      }
    },
    "simple_python - launch": {
      "adapter": "python",
      "configuration": {
        "name": "Python: Current File",
        "type": "python",
        "request": "launch",
        "cwd": "${workspaceRoot}/support/test/python/simple_python",
        "stopOnEntry": true,
        "console": "externalTerminal",
        "debugOptions": [],
        "program": "${workspaceRoot}/support/test/python/simple_python/main.py"
      }
    },
    "simple_c_program - MS Attach": {
      "adapter": "cppdbg",
      "configuration": {
        "name": "(lldb) Attach",
        "type": "cppdbg",
        "request": "attach",
        "program": "${workspaceRoot}/support/test/cpp/simple_c_program/test",
        "MIMode": "lldb"
      }
    },
    "bashdb": {
      "adapter": "bashdb",
      "configuration": {
        "type": "bashdb",
        "request": "launch",
        "name": "Bash-Debug (simplest configuration)",
        "program": "$HOME/.vim/bundle/YouCompleteMe/install.sh",
        "args": [],
        "cwd": "$HOME/.vim/bundle/YouCompleteMe",
        "pathBash": "bash",
        "pathBashdb": "bashdb",
        "pathCat": "cat",
        "pathMkfifo": "mkfifo",
        "pathPkill": "pkill",
        "showDebugOutput": true,
        "trace": true
      }
    },
    "lldb launch": {
      "adapter": "lldb",
      "configuration": {
        "type": "lldb",
        "request": "launch",
        "name": "LLDB: Launch",
        "program": "$HOME/Development/vim/src/vim",
        "args": [],
        "cwd": "$HOME/Development/vim"
      }
    },
    "racerd": {
      "adapter": "lldb",
      "configuration": {
        "type": "lldb",
        "request": "launch",
        "name": "LLDB: Launch",
        "program": "$HOME/.vim/bundle/YouCompleteMe/third_party/ycmd/third_party/racerd/target/debug/racerd",
        "args": [
          "serve",
          "--port=12345",
          "--secret-file=secretfile"
        ],
        "cwd": "$HOME/.vim/bundle/YouCompleteMe/third_party/ycmd"
      }
    }
  }
}
```

**Expected behavior**
I would expect the script to install the chrome debugger gadget

**Actual behaviour**
```
OS = linux
gadget_dir = /home/quentin/.vim/pack/default/start/vimspector/gadgets/linux
usage: install_gadget.py [-h] [--all] [--force-all] [--enable-c] [--disable-c]
                         [--enable-python] [--disable-python] [--enable-tcl]
                         [--disable-tcl] [--force-enable-csharp]
                         [--enable-bash] [--disable-bash] [--enable-go]
                         [--disable-go] [--force-enable-node]
                         [--force-enable-typescript]
install_gadget.py: error: unrecognized arguments: --force-enable-chrome
```

**Environemnt**

* Output of `vim --version`

```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Sep 29 2019 22:27:49)
Included patches: 1-2102
Compiled by Arch Linux
Huge version with GTK3 GUI.  Features included (+) or not (-):
+acl               -farsi             -mouse_sysmouse    -tag_any_white
+arabic            +file_in_path      +mouse_urxvt       +tcl/dyn
+autocmd           +find_in_path      +mouse_xterm       +termguicolors
+autochdir         +float             +multi_byte        +terminal
-autoservername    +folding           +multi_lang        +terminfo
+balloon_eval      -footer            -mzscheme          +termresponse
+balloon_eval_term +fork()            +netbeans_intg     +textobjects
+browse            +gettext           +num64             +textprop
++builtin_terms    -hangul_input      +packages          +timers
+byte_offset       +iconv             +path_extra        +title
+channel           +insert_expand     +perl/dyn          +toolbar
+cindent           +job               +persistent_undo   +user_commands
+clientserver      +jumplist          +postscript        +vartabs
+clipboard         +keymap            +printer           +vertsplit
+cmdline_compl     +lambda            +profile           +virtualedit
+cmdline_hist      +langmap           +python/dyn        +visual
+cmdline_info      +libcall           +python3/dyn       +visualextra
+comments          +linebreak         +quickfix          +viminfo
+conceal           +lispindent        +reltime           +vreplace
+cryptv            +listcmds          +rightleft         +wildignore
+cscope            +localmap          +ruby/dyn          +wildmenu
+cursorbind        +lua/dyn           +scrollbind        +windows
+cursorshape       +menu              +signs             +writebackup
+dialog_con_gui    +mksession         +smartindent       +X11
+diff              +modify_fname      +sound             -xfontset
+digraphs          +mouse             +spell             +xim
+dnd               +mouseshape        +startuptime       -xpm
-ebcdic            +mouse_dec         +statusline        +xsmp_interact
+emacs_tags        +mouse_gpm         -sun_workshop      +xterm_clipboard
+eval              -mouse_jsbterm     +syntax            -xterm_save
+ex_extra          +mouse_netterm     +tag_binary        
+extra_search      +mouse_sgr         -tag_old_static    
   system vimrc file: "/etc/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "/etc/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -I/usr/include/gtk-3.0 -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/lib/libffi-3.2.1/include -I/usr/include/harfbuzz -I/usr/include/fribidi -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/gio-unix-2.0 -I/usr/include/libdrm -I/usr/include/atk-1.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -pthread  -D_FORTIFY_SOURCE=2  -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -D_REENTRANT  -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: gcc   -L. -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -fstack-protector-strong -rdynamic -Wl,-export-dynamic -Wl,-E -Wl,-rpath,/usr/lib/perl5/5.30/core_perl/CORE  -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -L/usr/local/lib -Wl,--as-needed -o vim   -lgtk-3 -lgdk-3 -lz -lpangocairo-1.0 -lpango-1.0 -lharfbuzz -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0  -lSM -lICE -lXt -lX11 -lXdmcp -lSM -lICE  -lm -ltinfo -lelf -lnsl    -lcanberra  -lacl -lattr -lgpm -ldl   -Wl,-E -Wl,-rpath,/usr/lib/perl5/5.30/core_perl/CORE -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -fstack-protector-strong -L/usr/local/lib  -L/usr/lib/perl5/5.30/core_perl/CORE -lperl -lpthread -ldl -lm -lcrypt -lutil -lc   -L/usr/lib -ltclstub8.6 -ldl -lz -lpthread -lm
```

* Output of `which vim`:

```
/usr/bin/vim
```

* Output of `:py3 pass`:

```
paste here
```

* Operating system: linux 5.3

**Additional context**
I fixed the problem by using the `--force-enable-typescript`.

Then i got an error saying that the downloaded content wasn't a tar archive.

I fixed the problem by changing the url of the typescript gadget.

Know my `.gadgets.json looks like this` :

```
{
  "adapters": {
    "chrome": {
      "command": [
        "node",
        "${gadgetDir}/debugger-for-chrome/out/src/chromeDebug.js"
      ],
      "name": "debugger-for-chrome",
      "type": "chrome"
    }
  }
}
```

And the debugger doesn't launch without any errors.

After taking a look a the extracted archive i found that `chromeDebug.js` doesn't exist, instead there is a `chromeDebug.ts` file.

I suppose that i must compile those typescript files to js with tsc/

**Comment by puremourning** [comment]
You're quite right, the command should be `--force-enable-typescript` (for now, that's clearly a mistake!)

But when I run it, it works.

```
BenMBP:vimspector ben$ ./install_gadget.py --force-enable-typescript
OS = macos
gadget_dir = /Users/ben/.vim/bundle/vimspector/gadgets/macos
Removing existing /Users/ben/.vim/bundle/vimspector/gadgets/macos/download/debugger-for-chrome/4.12.0/msjsdiag.debugger-for-chrome-4.12.0.tar.gz
Downloading https://marketplace.visualstudio.com/_apis/public/gallery/publishers/msjsdiag/vsextensions/debugger-for-chrome/4.12.0/vspackage to /Users/ben/.vim/bundle/vimspector/gadgets/macos/download/debugger-for-chrome/4.12.0/msjsdiag.debugger-for-chrome-4.12.0.tar.gz
Checksum for /Users/ben/.vim/bundle/vimspector/gadgets/macos/download/debugger-for-chrome/4.12.0/msjsdiag.debugger-for-chrome-4.12.0.tar.gz: 0df2fe96d059a002ebb0936b0003e6569e5a5c35260dc3791e1657d27d82ccf5
Extracting /Users/ben/.vim/bundle/vimspector/gadgets/macos/download/debugger-for-chrome/4.12.0/msjsdiag.debugger-for-chrome-4.12.0.tar.gz to /Users/ben/.vim/bundle/vimspector/gadgets/macos/download/debugger-for-chrome/4.12.0/root
Removing dir /Users/ben/.vim/bundle/vimspector/gadgets/macos/download/debugger-for-chrome/4.12.0/root
x extension.vsixmanifest
x [Content_Types].xml
x extension/.github/assignment.yml
x extension/.github/locker.yml
x extension/.github/needs_more_info.yml
x extension/.gitignore
x extension/.npmignore
x extension/.vsts/.vsts-ci.yml
x extension/.vsts/job.yml

...
```

**Comment by ladevieq** [comment]
I just removed and clone again vimspector and this is the exact error i got

```
OS = linux
gadget_dir = /home/quentin/.vim/pack/default/start/vimspector/gadgets/linux
Downloading https://marketplace.visualstudio.com/_apis/public/gallery/publishers/msjsdiag/vsextensions/debugger-for-chrome/4.12.0/vspackage to /home/quentin/.vim/pack/default/start/vimspector/gadgets/linux/download/debugger-for-chrome/4.12.0/msjsdiag.debugger-for-chrome-4.12.0.tar.gz
Checksum for /home/quentin/.vim/pack/default/start/vimspector/gadgets/linux/download/debugger-for-chrome/4.12.0/msjsdiag.debugger-for-chrome-4.12.0.tar.gz: 0df2fe96d059a002ebb0936b0003e6569e5a5c35260dc3791e1657d27d82ccf5
Extracting /home/quentin/.vim/pack/default/start/vimspector/gadgets/linux/download/debugger-for-chrome/4.12.0/msjsdiag.debugger-for-chrome-4.12.0.tar.gz to /home/quentin/.vim/pack/default/start/vimspector/gadgets/linux/download/debugger-for-chrome/4.12.0/root
tar: This does not look like a tar archive
tar: Skipping to next header
tar: Exiting with failure status due to previous errors
Traceback (most recent call last):
  File "./install_gadget.py", line 437, in ExtractZipTo
    with tarfile.open( file_path ) as f:
  File "/usr/lib/python3.7/tarfile.py", line 1578, in open
    raise ReadError("file could not be opened successfully")
tarfile.ReadError: file could not be opened successfully

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./install_gadget.py", line 556, in <module>
    format = gadget[ 'download' ].get( 'format', 'zip' ) )
  File "./install_gadget.py", line 444, in ExtractZipTo
    subprocess.check_call( [ 'tar', 'zxvf', file_path ] )
  File "/usr/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['tar', 'zxvf', '/home/quentin/.vim/pack/default/start/vimspector/gadgets/linux/download/debugger-for-chrome/4.12.0/msjsdiag.debugger-for-chrome-4.12.0.tar.gz']' returned non-zero exit status 2.
FAILED installing debugger-for-chrome: Command '['tar', 'zxvf', '/home/quentin/.vim/pack/default/start/vimspector/gadgets/linux/download/debugger-for-chrome/4.12.0/msjsdiag.debugger-for-chrome-4.12.0.tar.gz']' returned non-zero exit status 2.
Traceback (most recent call last):
  File "./install_gadget.py", line 586, in <module>
    ','.join( failed ) ) )
RuntimeError: Failed to install gadgets: debugger-for-chrome
```

**Comment by puremourning** [comment]
what python version are you running `install_gadget.py` with ?

**Comment by ladevieq** [comment]
I'm using python 3.7

**Comment by puremourning** [comment]
Curious. Can you try running tar manually o `/home/quentin/.vim/pack/default/start/vimspector/gadgets/linux/download/debugger-for-chrome/4.12.0/msjsdiag.debugger-for-chrome-4.12.0.tar.gz`

e.g. 

* `mkdir tmp`
* `cd tmp`
*  `tar zxvf /home/quentin/.vim/pack/default/start/vimspector/gadgets/linux/download/debugger-for-chrome/4.12.0/msjsdiag.debugger-for-chrome-4.12.0.tar.gz`

It seems that neither python's `tarfile` module nor your system `tar` command could extract the downloaded file (though the file's checksum matches mine). 

I'll try in a linux vm too.

**Comment by puremourning** [comment]
Oh ok I can repro in the container used for CI (`puremourning/vimspector:manual`).

Turns out, for reasons only understood by Microsoft, these packages are actually gzip'd zip files.

Because, why not gzip a zip. Apparently macOS's tar can handle this, but (reasonably) linux can't.

I'll see what I can do.

**Comment by puremourning** [comment]
OK I have a fix for this. I will also make sure CI installs all of the 'unsupported' tools too to prevent this happening again.
