### ISSUE TITLE
Failing to launch with vim 9.0 + Python 3.7

### ISSUE THREAD

**Issue by angelaambroz** [puremourning/vimspector#716]
### Description

When I launch vimspector, the windows pop up - empty - and I see the message `Can't send message: Job is not running `. 

When reproducing using the minimal vimrc, the message is slightly different: same empty windows, but this time `Request for initialize aborted: Closing down`. 

### Works in vim?

Reproducable in Vim

### Works with clean config?

Yes

### Sample project works?

Not reproducable with sample project

### Minimal Reproduction

List of steps to reproduce:

1. Run `vim ---clean Nu /path/to/vimspector/support/minimal_vimrc support/test/python/simple_python/main.py`
2. Press F5 to launch.
3. Press 5 to select the `run` configuration. 

### Expected Behaviour

That I can then step through and use vimspector (as I have before). 

### Actual Behaviour

`Request for initialize aborted: Closing down`. 

### Installation Type

Plugin Manager (git clone)

### Vimspector version

ecf0c51b07ffedeca054581623bdda0d458e39d2

### Debug Info

```Text
`Vimspector not connected, start a debug session first`
```

### Log file

```Text
1 2023-02-02 17:14:14,655 - INFO - **** INITIALISING NEW VIMSPECTOR SESSION ****
  2 2023-02-02 17:14:14,655 - INFO - API is: 
  3 2023-02-02 17:14:14,655 - INFO - VIMSPECTOR_HOME = /home/work/.vim/bundle/vimspector/python3/vimspector/../..
  4 2023-02-02 17:14:14,656 - INFO - gadgetDir = /home/work/.vim/bundle/vimspector/gadgets/linux
  5 2023-02-02 17:14:14,656 - INFO - User Msg: Vimspector not connected, start a debug sessionfirst
  6 2023-02-02 17:14:17,242 - INFO - User requested start debug session with {}
  7 2023-02-02 17:14:17,243 - DEBUG - Reading configurations from: None
  8 2023-02-02 17:14:17,243 - DEBUG - Reading configurations from: /home/work/work/work_api/.vimspector.json
  9 2023-02-02 17:14:17,244 - DEBUG - Reading gadget config: /home/work/.vim/bundle/vimspector/gadgets/linux/.gadgets.json
 10 2023-02-02 17:14:17,245 - DEBUG - Reading gadget config: None
 11 2023-02-02 17:14:17,245 - INFO - Configuration: {"adapter": "debugpy", "breakpoints": {"ex    ception": {"caught": "", "uncaught": "Y"}}, "configuration": {"request": "launch", "python    ": "/home/work/.virtualenvs/work_api/bin/python3.7", "stopOnEntry": true, "console":"integratedTerminal", "program": "/home/work/work/work_api/work/tasks/tests/t    est_experimentation.py", "cwd": "/home/work/work/work_api"}}
 12 2023-02-02 17:14:17,245 - INFO - Adapter: {"command": ["/usr/bin/python3", "/home/work/    .vim/bundle/vimspector/gadgets/linux/debugpy/build/lib/debugpy/adapter"], "configuration":{"python": "/usr/bin/python3", "subProcess": false}, "name": "debugpy"}
 13 2023-02-02 17:14:17,252 - DEBUG - min_width/height: 149/50, actual: 94/54 - result: vertic    al
 14 2023-02-02 17:14:17,416 - DEBUG - LAUNCH!
 15 2023-02-02 17:14:17,417 - INFO - Starting debug adapter with: {"command": ["/usr/bin/python3", "/home/work/.vim/bundle/vimspector/gadgets/linux/debugpy/build/lib/debugpy/adapter"], "configuration": {"python": "/usr/bin/python3", "subProcess": false}, "name": "debugpy"}
 16 2023-02-02 17:14:17,417 - DEBUG - Connection Type: job
 17 2023-02-02 17:14:17,486 - INFO - Debug Adapter Started
 18 2023-02-02 17:14:17,487 - DEBUG - Sending Message: {"command": "initialize", "arguments":{"adapterID": "debugpy", "clientID": "vimspector", "clientName": "vimspector", "linesStart    At1": true, "columnsStartAt1": true, "locale": "en_GB", "pathFormat": "path", "supportsVar    iableType": true, "supportsVariablePaging": false, "supportsRunInTerminalRequest": true, "    supportsMemoryReferences": true}, "seq": 0, "type": "request"}
 19 2023-02-02 17:14:17,488 - INFO - The server has terminated with status 1
 20 2023-02-02 17:14:17,488 - DEBUG - Closing down: Aborting request {'command': 'initialize','arguments': {'adapterID': 'debugpy', 'clientID': 'vimspector', 'clientName': 'vimspector    ', 'linesStartAt1': True, 'columnsStartAt1': True, 'locale': 'en_GB', 'pathFormat': 'path'    , 'supportsVariableType': True, 'supportsVariablePaging': False, 'supportsRunInTerminalReq    uest': True, 'supportsMemoryReferences': True}, 'seq': 0, 'type': 'request'}
 21 2023-02-02 17:14:17,488 - INFO - User Msg: Request for initialize aborted: Closing down
 22 2023-02-02 17:14:17,492 - DEBUG - No server exit handler
 23 2023-02-02 17:14:21,396 - INFO - User Msg: Vimspector not connected, start a debug sessionfirst
```

### Vim version

```Text
❯ vim --version                                                                     
VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Feb  2 2023 16:33:05)
Included patches: 1-1274
Compiled by [xxx]@aambroz-dev
Huge version with GTK2 GUI.  Features included (+) or not (-):
+acl               +file_in_path      +mouse_urxvt       -tag_any_white
+arabic            +find_in_path      +mouse_xterm       -tcl
+autocmd           +float             +multi_byte        +termguicolors
+autochdir         +folding           +multi_lang        +terminal
-autoservername    -footer            -mzscheme          +terminfo
+balloon_eval      +fork()            +netbeans_intg     +termresponse
+balloon_eval_term +gettext           +num64             +textobjects
+browse            -hangul_input      +packages          +textprop
++builtin_terms    +iconv             +path_extra        +timers
+byte_offset       +insert_expand     -perl              +title
+channel           +ipv6              +persistent_undo   +toolbar
+cindent           +job               +popupwin          +user_commands
+clientserver      +jumplist          +postscript        +vartabs
+clipboard         +keymap            +printer           +vertsplit
+cmdline_compl     +lambda            +profile           +vim9script
+cmdline_hist      +langmap           -python            +viminfo
+cmdline_info      +libcall           +python3           +virtualedit
+comments          +linebreak         +quickfix          +visual
+conceal           +lispindent        +reltime           +visualextra
+cryptv            +listcmds          +rightleft         +vreplace
+cscope            +localmap          -ruby              +wildignore
+cursorbind        -lua               +scrollbind        +wildmenu
+cursorshape       +menu              +signs             +windows
+dialog_con_gui    +mksession         +smartindent       +writebackup
+diff              +modify_fname      -sodium            +X11
+digraphs          +mouse             -sound             -xfontset
+dnd               +mouseshape        +spell             +xim
-ebcdic            +mouse_dec         +startuptime       -xpm
+emacs_tags        -mouse_gpm         +statusline        +xsmp_interact
+eval              -mouse_jsbterm     -sun_workshop      +xterm_clipboard
+ex_extra          +mouse_netterm     +syntax            -xterm_save
+extra_search      +mouse_sgr         +tag_binary        
-farsi             -mouse_sysmouse    -tag_old_static    
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK -pthread -I/usr/include/gtk-2.0 -I/usr/lib/x86_64-linux-gnu/gtk-2.0/include -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/freetype2 -I/usr/include/libpng16 -g -O2 -D_REENTRANT -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 
Linking: gcc -L/usr/local/lib -Wl,--as-needed -o vim -lgtk-x11-2.0 -lgdk-x11-2.0 -lpangocairo-1.0 -latk-1.0 -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lpangoft2-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lfontconfig -lfreetype -lSM -lICE -lXt -lX11 -lXdmcp -lSM -lICE -lm -ltinfo -lrt -ldl -L/usr/lib/python3.7/config-3.7m-x86_64-linux-gnu -lpython3.7m -lcrypt -lpthread -ldl -lutil -lm
```

### Python version

3.7.5 (default, Dec  9 2021, 17:04:37) [GCC 8.4.0]

### Operating System

Linux aambroz-dev 5.4.0-1081-gke #87-Ubuntu SMP Thu Aug 18 05:22:40 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Declaration

- [X] I have read and understood [CONTRIBUTING.md](https://github.com/puremourning/vimspector/blob/master/CONTRIBUTING.md#diagnostics)
- [X] I have read and understood the [CODE_OF_CONDUCT.md](https://github.com/puremourning/vimspector/blob/master/CODE_OF_CONDUCT.md)

**Comment by puremourning** [comment]
Does it show anything in the 'server' tab of the Output window?

>  19 2023-02-02 17:14:17,488 - INFO - The server has terminated with status 1

The server (debugpy) is failing to start.

You can also try to start it manually from the command line to see why it's faliing:

```
/usr/bin/python3 /home/work/.vim/bundle/vimspector/gadgets/linux/debugpy/build/lib/debugpy/adapter
```

**Comment by angelaambroz** [comment]
Ah ha - thanks. 

```
❯ /usr/bin/python3 /home/work/.vim/bundle/vimspector/gadgets/linux/debugpy/build/lib/debugpy/adapter
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/work/.vim/bundle/vimspector/gadgets/linux/debugpy/build/lib/debugpy/adapter/__main__.py", line 212, in <module>
    __import__("debugpy")
  File "/home/work/.vim/bundle/vimspector/gadgets/linux/debugpy/build/lib/debugpy/adapter/../../debugpy/__init__.py", line 28, in <module>
    "Python 3.6 and below is not supported by this version of debugpy; "
AssertionError: Python 3.6 and below is not supported by this version of debugpy; use debugpy 1.5.1 or earlier.
```

OK, that's probably on me to fix - argh, Python ecosystem!

**Comment by angelaambroz** [comment]
Yep - symlinked to Python3.7 and it's working as expected now. Thanks!

**Comment by puremourning** [comment]
> - argh, Python ecosystem!

tell me about it :(

glad it's resolved.
