### ISSUE TITLE
raise NameError when creating new tab in Neovim.

### ISSUE THREAD

**Issue by KPatr1ck** [puremourning/vimspector#754]
### Description

Reproduce when creating a new tab by `tabnew`.

```python
Error detected while processing TabEnter Autocommands for "*"..function vimspector#internal#state#OnTabEnter[7]..provider#python3#Call:
line   18:
Error invoking 'python_execute' on channel 5 (python3-script-host):
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name '_vimspector_session_man' is not defined
```

### Works in vim?

Only broken in Neovim

### Works with clean config?

Yes

### Sample project works?

Not reproducable with sample project

### Minimal Reproduction

List of steps to reproduce:

1. Run `vim ---clean Nu /path/to/vimspector/support/minimal_vimrc ....`
2. Open _this project_...
3. Press _this sequence of keys_

### Expected Behaviour

Open new tab.

### Actual Behaviour

```python
Error detected while processing TabEnter Autocommands for "*"..function vimspector#internal#state#OnTabEnter[7]..provider#python3#Call:
line   18:
Error invoking 'python_execute' on channel 5 (python3-script-host):
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name '_vimspector_session_man' is not defined
```

### Installation Type

Plugin Manager (git clone)

### Vimspector version

544c7aff5a9434f985bb0715d996cb2c45506edf

### Vim version

```Text
NVIM v0.9.0-dev-1023+g649742821
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wno-unused-result -Wimplicit-fallthrough -Wvla -fno-common -fdiagnostics-color=always -fstack-protector-strong -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DMIN_LOG_LEVEL=3 -DNVIM_UNIBI_HAS_VAR_FROM -I/home/cxj/neovim/.deps/usr/include/luajit-2.1 -I/usr/include -I/home/cxj/neovim/.deps/usr/include -I/home/cxj/neovim/.deps/usr/include -I/home/cxj/neovim/.deps/usr/include -I/home/cxj/neovim/.deps/usr/include -I/home/cxj/neovim/build/src/nvim/auto -I/home/cxj/neovim/build/include -I/home/cxj/neovim/build/cmake.config -I/home/cxj/neovim/src -I/home/cxj/neovim/.deps/usr/include -I/home/cxj/neovim/.deps/usr/include -I/home/cxj/neovim/.deps/usr/include

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
```

### Declaration

- [X] I have read and understood [CONTRIBUTING.md](https://github.com/puremourning/vimspector/blob/master/CONTRIBUTING.md#diagnostics)
- [X] I have read and understood the [CODE_OF_CONDUCT.md](https://github.com/puremourning/vimspector/blob/master/CODE_OF_CONDUCT.md)

**Comment by puremourning** [comment]
Thanks for the report. Fixing now.
