### ISSUE TITLE
install_gadget.py fails for nodejs

### ISSUE THREAD

**Issue by bag-man** [puremourning/vimspector#78]
I don't have time to submit a full nice bug report, but just thought I would throw this out there so it is at least mildly documented. When installing the node gadget, it fails on submodule initialisation. 

As a work around I commented out lines 503-508 in install_gadget.py, and ran it again. Running the submodule commands in those repos returned exit code 0, and didn't appear to do anything. 

I can update with more details tomorrow if needed. 

```
.vim λ python ~/.vim/plugged/vimspector/install_gadget.py --force-enable-node
OS = linux
gadget_dir = /home/owg1/.vim/plugged/vimspector/gadgets/linux
Cloning into '/home/owg1/.vim/plugged/vimspector/gadgets/linux/download/vscode-node-debug2'...
remote: Enumerating objects: 169, done.
remote: Counting objects: 100% (169/169), done.
remote: Compressing objects: 100% (115/115), done.
remote: Total 4507 (delta 105), reused 104 (delta 54), pack-reused 4338
Receiving objects: 100% (4507/4507), 1.50 MiB | 3.29 MiB/s, done.
Resolving deltas: 100% (2842/2842), done.
Note: switching to 'v1.39.1'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at cc55960 1.39.1
fatal: not a git repository (or any of the parent directories): .git
Traceback (most recent call last):
  File "/home/owg1/.vim/plugged/vimspector/install_gadget.py", line 605, in <module>
    CloneRepoTo( url, ref, destination )
  File "/home/owg1/.vim/plugged/vimspector/install_gadget.py", line 503, in CloneRepoTo
    subprocess.check_call( [ 'git', 'submodule', 'sync', '--recursive' ] )
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['git', 'submodule', 'sync', '--recursive']' returned non-zero exit status 128.
FAILED installing vscode-node-debug2: Command '['git', 'submodule', 'sync', '--recursive']' returned non-zero exit status 128.
Traceback (most recent call last):
  File "/home/owg1/.vim/plugged/vimspector/install_gadget.py", line 637, in <module>
    raise RuntimeError( 'Failed to install gadgets: {}'.format(
RuntimeError: Failed to install gadgets: vscode-node-debug2
.vim λ ls /home/owg1/.vim/plugged/vimspector/gadgets/linux/download/vscode-node-debug2
total 352K
drwxr-xr-x 12 owg1 owg1 4,0K  9 jan 16.52 .
drwxr-xr-x  3 owg1 owg1 4,0K  9 jan 16.52 ..
drwxr-xr-x  8 owg1 owg1 4,0K  9 jan 16.52 .git
drwxr-xr-x  2 owg1 owg1 4,0K  9 jan 16.52 .github
drwxr-xr-x 16 owg1 owg1 4,0K  9 jan 16.52 i18n
drwxr-xr-x  2 owg1 owg1 4,0K  9 jan 16.52 images
drwxr-xr-x  2 owg1 owg1 4,0K  9 jan 16.52 msbuild
drwxr-xr-x  2 owg1 owg1 4,0K  9 jan 16.52 src
drwxr-xr-x  2 owg1 owg1 4,0K  9 jan 16.52 test
drwxr-xr-x 27 owg1 owg1 4,0K  9 jan 16.52 testdata
drwxr-xr-x  2 owg1 owg1 4,0K  9 jan 16.52 .vscode
drwxr-xr-x  2 owg1 owg1 4,0K  9 jan 16.52 .vsts
-rw-r--r--  1 owg1 owg1  333  9 jan 16.52 CODE_OF_CONDUCT.md
-rw-r--r--  1 owg1 owg1  960  9 jan 16.52 CONTRIBUTING.md
-rw-r--r--  1 owg1 owg1  170  9 jan 16.52 .gitignore
-rw-r--r--  1 owg1 owg1 6,2K  9 jan 16.52 gulpfile.js
-rw-r--r--  1 owg1 owg1 1,2K  9 jan 16.52 LICENSE.txt
-rw-r--r--  1 owg1 owg1  17K  9 jan 16.52 package.json
-rw-r--r--  1 owg1 owg1 230K  9 jan 16.52 package-lock.json
-rw-r--r--  1 owg1 owg1 4,4K  9 jan 16.52 package.nls.json
-rw-r--r--  1 owg1 owg1  906  9 jan 16.52 README.md
-rw-r--r--  1 owg1 owg1 1,5K  9 jan 16.52 ThirdPartyNotices.txt
-rw-r--r--  1 owg1 owg1  464  9 jan 16.52 tsconfig.json
-rw-r--r--  1 owg1 owg1 2,0K  9 jan 16.52 tslint.json
-rw-r--r--  1 owg1 owg1  813  9 jan 16.52 .vscodeignore
.vim λ
```

**Comment by puremourning** [comment]
Does it work if you run it with cwd of ` ~/.vim/plugged/vimspector/` ?

**Comment by puremourning** [comment]
Actually, nevermind, you're right, it's just broken

```
  subprocess.check_call( [ 'git', 'submodule', 'sync', '--recursive' ] )
  subprocess.check_call( [ 'git',
                           'submodule',
                           'update',
                           '--init',
                           '--recursive' ] )

```

They need to use `-C <destination>`. I'll fix it.

Thansk for the report!

**Comment by bag-man** [comment]
Awesome, thanks for the quick fix! :D
